import type { Client, ClientFilter } from "./client-types";

export const clients: Client[] = [
  {
    id: "CL-001",
    name: "Arman Khan",
    email: "arman@example.com",
    initials: "AK",
    status: "Lead",
    type: "Automation",
    requests: 1,
    projects: 0,
    lastActivity: "Today, 9:42 PM",
    lastSubject: "Automating our daily workflow",
  },
  {
    id: "CL-002",
    name: "Sara Mehta",
    email: "sara@example.com",
    initials: "SM",
    status: "Lead",
    type: "Automation",
    requests: 1,
    projects: 0,
    lastActivity: "Sep 26, 2026",
    lastSubject: "Client reporting automation",
  },
  {
    id: "CL-003",
    name: "Dev Patel",
    email: "dev@example.com",
    initials: "DP",
    status: "Lead",
    type: "AI System",
    requests: 1,
    projects: 0,
    lastActivity: "Sep 25, 2026",
    lastSubject: "AI assistant for internal operations",
  },
  {
    id: "CL-004",
    name: "Mira Shah",
    email: "mira@example.com",
    initials: "MS",
    status: "Active",
    type: "Website",
    requests: 1,
    projects: 1,
    lastActivity: "Sep 21, 2026",
    lastSubject: "Website redesign and build",
  },
  {
    id: "CL-005",
    name: "Zoya Ali",
    email: "zoya@example.com",
    initials: "ZA",
    status: "Completed",
    type: "Internal Tool",
    requests: 1,
    projects: 1,
    lastActivity: "Sep 24, 2026",
    lastSubject: "Internal operations dashboard",
  },
];

export const clientFilters: ClientFilter[] = [
  "All",
  "Lead",
  "Active",
  "Completed",
];
